import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import block from '../components/block'

export default function Feedback() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <main className="page">
        <div className="page__container container">
          <div className="feedback">
            <div className="feedback__title title">
              <h1>Обратная связь</h1>
            </div>
            <div className="feedback__block">
              <div className="form">
                <div className="form-input">
                    <div htmlFor="" className="form-input__title">ФИО</div>
                    <input type="text" className='form-input__form' id='name'/>
                </div>
                <div className="form-input">
                    <div htmlFor="" className="form-input__title">Адрес</div>
                    <input type="text" className='form-input__form' id='adress'/>
                </div>
                <div className="form-input">
                    <div htmlFor="" className="form-input__title">Телефон</div>
                    <input type="text" className='form-input__form' id='number' placeholder='+7'/>
                </div>
                <div className="form-input">
                    <div htmlFor="" className="form-input__title">E-mail</div>
                    <input type="text" className='form-input__form' id='email'/>
                </div>
              </div>
            </div>
            <div className="ancor">
              <div className="ancor__all-news">
                <div className="all-news-item"><a href="/home" className="link">Главная</a></div>
              </div>
              <div className="ancor__feedback">
                <div className="feedback"><a href="/news" className="link">Все Новости</a></div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
