import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Block from '../components/Block'
import { useState } from 'react'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <main className="page">
        <div className="page__container container">
          <div className="news">
            <div className="news__title title">
              <h1>Новости</h1>
            </div>
            <div className="news__block">
              <Block
                title='Новое предложение'
                subtitle='Ber hitär innan infranar. Multigt arade. Bede ogt. 
                          Monolosk etnotos i vagt. Kol os så operadiktisk. Sogt. 
                          Ohunas. Ultrar aniledes. Kompetensutvisning nöligt.'
                date=' дата публикации 1.7.2022' />
              <Block />
              <Block />
              <Block />
              <Block />
              <Block />
              <Block />
              <Block />
              <Block />
            </div>
            <div className="ancor">
              <div className="ancor__all-news">
                <div className="all-news-item"><a href="/news" className="link">Все новости</a></div>
              </div>
              <div className="ancor__feedback">
                <div className="feedback"><a href="/feedback" className="link">Обратная связь</a></div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
