import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Block from '../components/Block'
import Db from '../components/Db'

export default function News() {
  
  const Database = Db()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <main className="page">
        <div className="page__container container">
          <div className="news">
            <div className="news__title title">
              <h1>Все новости</h1>
            </div>
            <div className="news__block">
              {Database.map(a =>
                <Block
                  key={a.title}
                  title={a.title}
                  subtitle={a.subtitle} 
                  date={a.date}/>
              )}

            </div>
            <div className="ancor">
              <div className="ancor__all-news">
                <div className="all-news-item"><a href="/home" className="link">Главная</a></div>
              </div>
              <div className="ancor__feedback">
                <div className="feedback"><a href="/feedback" className="link">Обратная связь</a></div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
